---
# tasks file for kibana_install
     - name: Install required system packages
       apt:
        pkg:
          - apt-transport-https
          - wget
          - software-properties-common
          - default-jdk
        state: latest
        install_recommends: no
        update_cache: yes

     - name: Download Kibana
       get_url:
           url: https://storage.yandexcloud.net/drugov/ELK7/kibana-7.17.8-amd64.deb?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=YCAJEAvqBdVwYwsmpSHOunfAn%2F20230221%2Fru-central1%2Fs3%2Faws4_request&X-Amz-Date=20230221T180815Z&X-Amz-Expires=2592000&X-Amz-Signature=99C45ED2C41FAAB5818CB6F65206AF8C5CC1E7C3FC88E3A09571680C32FD6C01&X-Amz-SignedHeaders=host
           dest: /home/admin/

     - name: Install Kibana 
       apt:
         deb: /home/admin/kibana-7.17.8-amd64.deb

     - name: stop Kibana
       service:
         name: kibana
         enabled: yes
         state: stopped

     - name: Copy config file kibana
       template:
          src: kibana.yml.j2
          dest: /etc/kibana/kibana.yml          

     - name: restart Kibana
       service:
         name: kibana
         enabled: yes
         state: restarted
...