---
# tasks file for filebeat_mysite_install
     - name: Install required system packages
       apt:
        pkg:
          - apt-transport-https
          - wget
        state: latest
        update_cache: no

     - name: Download filebeat
       get_url:
           url: https://storage.yandexcloud.net/drugov/ELK7/filebeat-7.17.8-amd64.deb?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=YCAJEAvqBdVwYwsmpSHOunfAn%2F20230304%2Fru-central1%2Fs3%2Faws4_request&X-Amz-Date=20230304T154750Z&X-Amz-Expires=2592000&X-Amz-Signature=CA939AB6F19D034243B5AE60A7A6B0D660A73BB5A9511A0F777F8155BA299352&X-Amz-SignedHeaders=host
           dest: /home/admin/

     - name: Install filebeat
       apt:
         deb: /home/admin/filebeat-7.17.8-amd64.deb

     - name: Apply filebet template
       template:
        src: filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml

     - name: Change config
       lineinfile:
        path: /etc/filebeat/filebeat.yml
        regexp: '^\s*#username:'
        line: '  username: "elastic"'

     - name: Change config
       lineinfile:
        path: /etc/filebeat/filebeat.yml
        regexp: '^\s*#password:'
        line: '  password: "{{ password_elastic }}"'

     - name: Execute the command
       shell: filebeat modules enable nginx

     - name: Apply filebet_modul template
       template:
        src: nginx.yml.j2
        dest: /etc/filebeat/modules.d/nginx.yml

     - name: Execute the command
       shell:  filebeat setup --pipelines --modules nginx

     - name: Execute the command
       shell: filebeat modules enable system

     - name: Execute the command
       shell:  filebeat setup --pipelines --modules system

     - name: Execute the command
       shell:  filebeat setup --index-management -E output.logstash.enabled=false -E 'output.elasticsearch.hosts=["elasticsearch:9200"]'

     - name: Execute the command
       shell:  filebeat setup -E output.logstash.enabled=false -E output.elasticsearch.hosts=['elasticsearch:9200'] -E setup.kibana.host=kibana:5601

     - name: start filebeat
       service:
         name: filebeat
         enabled: yes
         state: started
...