---
# tasks file for prometheus_install
  
    - name: Prometheus install
      apt:
        name: prometheus
        state: latest
        update_cache: true

    - name: stop Prometheus
      systemd:
        name: prometheus
        state: stopped   

    - name: Copy config file
      template:
          src: prometheus.yml.j2
          dest: /etc/prometheus/prometheus.yml
          owner: root
          group: root
          mode: '0644'
          backup: yes

    - name: start Prometheus
      systemd:
        daemon_reload: true
        name: prometheus
        state: started
        enabled: yes
