---
# tasks file for elastic_install
     - name: Install required system packages
       apt:
        pkg:
          - apt-transport-https
          - wget
          - software-properties-common
          - default-jdk
          - python3-pexpect
        state: latest
        install_recommends: no
        update_cache: yes

     - name: Download Elasticsearch
       get_url:
           url: https://storage.yandexcloud.net/drugov/ELK7/elasticsearch-7.17.8-amd64.deb?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=YCAJEAvqBdVwYwsmpSHOunfAn%2F20230304%2Fru-central1%2Fs3%2Faws4_request&X-Amz-Date=20230304T161758Z&X-Amz-Expires=2592000&X-Amz-Signature=6818E2FE0E7A8BFFE4304B01E8B279DB18A878641739FC123C1B28F500F11250&X-Amz-SignedHeaders=host
           dest: /home/admin/

     - name: Install  Elasticsearch
       apt:
         update_cache: no
         deb: /home/admin/elasticsearch-7.17.8-amd64.deb

     - name: Copy config file Elasticsearch
       template:
          src: elasticsearch.yml.j2
          dest: /etc/elasticsearch/elasticsearch.yml

     - name: Start Elasticsearch
       service:
        name: elasticsearch
        enabled: yes
        state: started

     - name: Password
       expect:
        command: /usr/share/elasticsearch/bin/elasticsearch-setup-passwords interactive -b
        echo: true
        responses:
             (?i)password.*: "{{ password_elastic }}"
       notify: Restart Elasticsearch
...
