{
 "title": "Nginx",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "parse_errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysite_parse_errors_total[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_response_size_bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mysite_http_response_size_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_response_count_total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mysite_http_response_count_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}