---
# tasks file for mysite_install
    - name: install Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Restart Nginx
      service:
        name: nginx
        enabled: yes
        state: restarted

    - name: Copy site
      copy:
        src: "{{ app_root }}"
        dest: "{{ document_root }}"
        mode: preserve

    - name: delete default 
      file:
        path: /etc/nginx/sites-available/default
        state: absent

    - name: delete default 
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Apply Nginx template
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/mysite
      notify: Restart Nginx

    - name: Enable new site
      file:
        src: /etc/nginx/sites-available/mysite
        dest: /etc/nginx/sites-enabled/mysite
        state: link
      notify: Restart Nginx

    - name: Create Directories
      file:
        path: /var/log/nginx/mysite/
        state: directory
        
    - name: Change config
      lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: '^\s*# Logging Settings'
        line: log_format custom   '$remote_addr - $remote_user [$time_local] ' '"$request" $status $body_bytes_sent ' '"$http_referer" "$http_user_agent" "$http_x_forwarded_for"';
      notify: Restart Nginx

    - name: Change config
      lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: '^\s*access_log /var/log/nginx/access.log'
        line: access_log /var/log/nginx/mysite/access.log custom;
      notify: Restart Nginx

    - name: Change config
      lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: '^\s*error_log /var/log/nginx/error.log'
        line: error_log /var/log/nginx/mysite/error.log;
      notify: Restart Nginx  
