---
- name: Elastic
  hosts: elasticsearch
  roles:
    - elastic_install
    - node_exporter_install

- name: Prometheus
  hosts: prometheus
  roles:
    - prometheus_install
    - node_exporter_install

- name: Grafana
  hosts: grafana
  roles:
    - grafana_install
    - node_exporter_install

- name: Kibana
  hosts: kibana
  roles:
    - kibana_install
    - node_exporter_install

...
