---
- hosts: prometheus

  tasks: 
    - name: Prometheus install
      apt:
        name: prometheus
        state: latest
        update_cache: true

    - name: stop Prometheus
      systemd:
        name: prometheus
        state: stopped   

    - name: Copy config file
      template:
          src: files/prometheus.yml.j2
          dest: /etc/prometheus/prometheus.yml
          owner: root
          group: root
          mode: '0644'
          backup: yes

    - name: restart Prometheus
      systemd:
        daemon_reload: true
        name: prometheus
        state: started
        enabled: yes

- hosts: all
  tasks:

    - name: Localtime
      shell:  ln -sf /usr/share/zoneinfo/Europe/Moscow /etc/localtime


    - name: Install node-exporter
      apt:
        name: prometheus-node-exporter
        state: latest
        update_cache: true 
        